### PR TITLE
Added support for projects

### PR DESCRIPTION
**Pull request by peterdremstrup**
You can add projects to bitbucket in addition to adding a repository to existing projects.

I also added usage instructions to the README and added a note to help using the acceptance tests.

### CODE REVIEW

**Comment by peterdremstrup** [comment]
@cwood any chance you could take a look at this? I've got another one coming with .netrc support for credentials 😊

**Comment by tdi** [comment]
@peterdremstrup can you please try find to fix the conflicts?

**Comment by peterdremstrup** [comment]
Should be done now.

**Comment by tdi** [comment]
Not yet, fmt does not go for provider.go for some reason.

**Comment by cwood** [comment]
I have wrote and published this into terraform. Thanks for your support! https://www.terraform.io/docs/providers/bitbucket/index.html

**Pull request merged**
