### PR TITLE
Support for repository variables

### PR DESCRIPTION
**Pull request by tdi**
Hi Adding support for repository variables and enabling pipelines of a repository. Partially it addresses needs from #38.

### CODE REVIEW

**Comment by hronix** [comment]
Hi @chrisarcand, Could you please set exceptions to us what is the process of PR review and how long it can take to merge? We are looking to have this functionality in upstream and use in our work. Thanks!

**Comment by paultyng** [comment]
@hronix this provider is maintained by people at Bitbucket / Atlassian (specifically @cwood), if you would like to escalate the maintenance I'd recommend reaching out to your account/support representative there.

**Review by cwood — APPROVED** [review]

**Comment by cwood** [comment]
Sorry this is purely a 20% time project and I rarely get 20% time much anymore. This seems fine.

**Comment by tdi** [comment]
I will have more PRs coming :) Thanks for merging :)

**Comment by cwood** [comment]
I have wrote and published this into terraform. Thanks for your support! https://www.terraform.io/docs/providers/bitbucket/index.html

**Comment by tdmalone** [comment]
Possible regression: https://github.com/terraform-providers/terraform-provider-bitbucket/issues/58

**Pull request merged**
