### PR TITLE
Add bitbucket_branch_restriction resource

### PR DESCRIPTION
**Pull request by amatellanes**
This PR adds a `bitbucket_branch_restriction` resource for setting up branch restrictions for your repository:

```hcl
# Manage your repositories branch restrictions
resource "bitbucket_branch_restriction" "master" {
  owner      = "myteam"
  repository = "terraform-code"

  kind = "push"
  pattern = "master"
}
```
References:
* [Bitbucket API `branch-restrictions`](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/branch-restrictions)

### CODE REVIEW

**Comment by stefanthorpe** [comment]
@radeksimko @cwood @grubernaut 
Just wondering who needs to review this PR?

**Comment by cwood** [comment]
Sorry. I just saw this. This seems fine to me.

**Comment by tongpu** [comment]
It would be awesome if we could get this merged. It's the missing piece that would allow us to manage all repository permission in Terraform!

**Comment by amatellanes** [comment]
@cwood I've just resolved conflicts. Any news about merging these changes?

**Comment by cwood** [comment]
I actually plan on working on this provider this week since I can use my 20% time to take over this. Ill take a look at it today/tomorrow. :) Thanks for the contribution.

**Comment by httpoz** [comment]
Hey @cwood did you get a chance to take a look? :)

**Comment by iridian-ks** [comment]
@cwood was wondering when this could get merged in?

**Comment by tdi** [comment]
@amatellanes can you find time to resolve the new conflicts ?

**Comment by amatellanes** [comment]
Done ✔️ @tdi

**Comment by amatellanes** [comment]
Thanks for merging my changes @cwood 

Any chance to update documentation [here](https://www.terraform.io/docs/providers/bitbucket/) to show new resources added?

**Comment by cwood** [comment]
Im currently doing that now.

**Comment by cwood** [comment]
I have wrote and published this into terraform. Thanks for your support! https://www.terraform.io/docs/providers/bitbucket/index.html

**Pull request merged**
